d/s only - adjust check for os-release on CentOS Stream CoreOS (csco)
CSCO does not define "$RHEL_VERSION" in "/etc/os-release" (anymore?).
This leads to a failure to detect the OS and an error

   ERROR: RHEL Major Version Unsupported, rhelmajor=

Instead, fallback to "$PLATFORM_ID".

Also, use "echo" instead of "log". No such command exists.

https://issues.redhat.com/browse/OCPBUGS-44313

Fixes: 2e59250eaf36 ('d/s only - build for RHEL8 and RHEL9')
(cherry picked from commit c291f50b5311225a4993a27a3a5c78eb5b523bb0)